# MIT License
# Copyright (c) 2024 Alexei Snitkovski <sam@1c.ro> and colleagues
# 
# Создание и настройка персонального токена доступа (PAT):
#   - Перейдите в Developer settings
#   - Нажмите Generate new token
#   - Дайте токену подходящее имя
#   - Выберите следующие разрешения:
#       Contents:  Repository contents, commits, branches, downloads, releases, and merges
#       Pages:     Retrieve Pages statuses, configuration, and builds, as well as create new builds
#       Workflows: Update GitHub Action workflow files
#   - Создайте токен и скопируйте его
#
# Добавление токена как секрета:
#   - Перейдите в настройки вашего репозитория (Settings)
#   - Выберите раздел Secrets and variables -> Actions
#   - Нажмите New repository secret
#   - Назовите секрет, например, PERSONAL_ACCESS_TOKEN, и вставьте туда созданный токен.
#

name: Generate and Publish Allure Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      # Install Allure
      - name: Install Allure
        run: |
          # Install Allure
          ALLURE_VERSION=2.17.2
          wget -qO- https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.tgz | tar -xz -C /opt/
          echo "/opt/allure-${ALLURE_VERSION}/bin" >> $GITHUB_PATH

      # Generate Allure Report
      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
